import { Provider } from "@/components/theme-provider"
import { Navbar } from "@/components/Navbar"
import { Links } from "@/components/Links"
import './globals.css'

export const metadata = {
    title: 'Wendy Huang | Pianist | Coder Sloth',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Provider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
      <div className="grid grid-cols-1 md:flex min-h-screen flex-row justify-between p-12">

      {/* <div className="flex min-h-screen flex-row justify-between p-12"> */}
          <div><Links /></div>
          <div>{children}</div>
          <Navbar />
      </div>
      </Provider>
      <script
        src="https://product-gallery.cloudinary.com/all.js"
        type="text/javascript"
        async
      >
        <script async src="https://polyfill.io/v3/polyfill.min.js?features=default%2Cfetch%2CArray.prototype.includes%2CObject.values%2CArray.prototype.find%2CNumber.isInteger"></script>
      </script>
      </body>
    </html>
  )
}
